name: axikernels_env
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.12
  - pyyaml
  - obspy
  - pandas
  - netcdf4
  - cartopy
  - mpmath
  - mayavi
  - xarray
  - tqdm
  - plotly
  - basemap
  - ruamel
  - ruamel.yaml
  - pytables
