package:
  name: axikernels
  version: 0.1

source:
  path: .

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/Adrian-Mag/AxiSEM3D_Kernels.git
  license: MIT
  summary: 'A Python package for handling Axisem3D output'

extra:
  recipe-maintainers:
    - Adrian Mag